/* Generated by Cython 0.29.37 */

#ifndef __PYX_HAVE__quickquant__module
#define __PYX_HAVE__quickquant__module

#include "Python.h"

#ifndef __PYX_HAVE_API__quickquant__module

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double add(double, double);

#endif /* !__PYX_HAVE_API__quickquant__module */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmodule(void);
#else
PyMODINIT_FUNC PyInit_module(void);
#endif

#endif /* !__PYX_HAVE__quickquant__module */
